### ISSUE TITLE
Attention in the model?

### ISSUE THREAD

**Issue by fawazsammani** [ntrang086/image_captioning#1]
Hi. You mentioned that your implementation includes: Show, Attend and Tell.
But I don't see any Attention implementation in your code. So may I know if your code does provide Attention mechanism in any place? And is it possible you can upload the trained models also?

**Comment by ntrang086** [comment]
Hello there! I haven't used Attention yet. I'm quite busy right now, but I plan to come back to this project in the future and try out Attention. I referenced the Show, Attend and Tell paper for other things, e.g. the use of Adam optimizer for the MS COCO dataset, using BLEU score for validation, etc. 
Can you clarify what you meant by the "the trained models"? Did you mean the ".pkl" files that I saved after each epoch?

**Comment by fawazsammani** [comment]
Hello.
Thank you for your fast answer. And for your tutorial as well. I'm really
enjoying it. Yes, I mean by the trained model the .pkl weights you saved.
Do you still have them? Thanks

**Comment by ntrang086** [comment]
You’re welcome. I’m afraid I don’t have these .pkl files anymore. But I remember the best epoch was #4 and the model stopped training at epoch #7 due to my early stopping condition. So if you use my current model and hyperparameter settings you can just train the model until epoch #4. Of course there are opportunities for improvement with my current model so if you make some enhancements and have computational resources you’re recommended to train for more epochs.

**Comment by fawazsammani** [comment]
Alright. Thanks very much
Most importantly, thnks for the tutorial, you arranged it in a great way. I
will make sure to cite your code in any further projects I do.

Regards
